spring:
  application:
    name: accommodation-marketplace
  datasource:
    url: ${ jdbc:mysql://localhost:3306/ }
    user: ${ root }
    password: ${ root }
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  cache:
    type: caffeine

  security:
    oauth2:

